### ISSUE TITLE
Chapter 04: Deep CNNs AlexNet - something going on? (cudaMalloc)

### ISSUE THREAD

**Issue by SumNeuron** [zackchase/mxnet-the-straight-dope#361]
So I was going through the straight dope tutorial for [Deep CNNs](http://gluon.mxnet.io/chapter04_convolutional-neural-networks/deep-cnns-alexnet.html) and tried implementing this (i.e. copy paste). 

Now this would not run on my local machine as is and this might be because I have 2 tiny Quadros (K620 and K2000). This is consistently because of running out of memory (cudaMalloc). 

So I had a friend run it on their dgx1 (8 brand new volta gpus) after I modified the training loop in conjunction with the code outlined from [multiple gpus with gluon](http://gluon.mxnet.io/chapter07_distributed-learning/multiple-gpus-gluon.html).

Now this still does not run with 1 gpu... or 2... or 4. It runs with all 8, and results in a consistent validation accuracy of 0.1.

So is the CIFAR10 dataset really that big... or is this something wonky with the `DataLoader`

Other notes:

-  how do I fix [17:21:53] src/kvstore/././comm.h:327: only 32 out of 56 GPU pairs are enabled direct access. It may affect the performance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off

- please add a high level interface to force clear all allocated memory on a give gpu

# *DataLoader 
 - Why does the DataLoader not return a data iterator?

This means any training loop that is built around the data iterator structure has to be modified.
It is minor to do, but it is somewhat obnoxious to always have to comment out `.reset()` and switch for loop statements (e.g. `for batch in train_data` vs `for batch_num, (data, labels) in enumerate(train_data)`)

- Also, can you guys please add a local load option. Once we download the data, it shouldn't always try to get the data from a remote source. 

-----------------

# Multi-GPU Alex Net code
```
from __future__ import print_function
import mxnet as mx
from mxnet import nd, autograd
from mxnet import gluon
import numpy as np
mx.random.seed(1)
from time import time
import json

def transformer(data, label):
    data = mx.image.imresize(data, 224, 224)
    data = mx.nd.transpose(data, (2,0,1))
    data = data.astype(np.float32)
    return data, label

batch_size = 64

print('[LOAD]: CIFAR10 TRAIN')
train_data = gluon.data.DataLoader(
    gluon.data.vision.CIFAR10('./data', train=True, transform=transformer),
    batch_size=batch_size, shuffle=True, last_batch='discard')
print('[LOADED]')

print('[LOAD]: CIFAR10 TEST')
test_data = gluon.data.DataLoader(
    gluon.data.vision.CIFAR10('./data', train=False, transform=transformer),
    batch_size=batch_size, shuffle=False, last_batch='discard')
print('[LOADED]')



print('[DEF]: ALEX NET')
alex_net = gluon.nn.Sequential()
with alex_net.name_scope():
    #  First convolutional layer
    alex_net.add(gluon.nn.Conv2D(channels=96, kernel_size=11, strides=(4,4), activation='relu'))
    alex_net.add(gluon.nn.MaxPool2D(pool_size=3, strides=2))
    #  Second convolutional layer
    alex_net.add(gluon.nn.Conv2D(channels=192, kernel_size=5, activation='relu'))
    alex_net.add(gluon.nn.MaxPool2D(pool_size=3, strides=(2,2)))
    # Third convolutional layer
    alex_net.add(gluon.nn.Conv2D(channels=384, kernel_size=3, activation='relu'))
    # Fourth convolutional layer
    alex_net.add(gluon.nn.Conv2D(channels=384, kernel_size=3, activation='relu'))
    # Fifth convolutional layer
    alex_net.add(gluon.nn.Conv2D(channels=256, kernel_size=3, activation='relu'))
    alex_net.add(gluon.nn.MaxPool2D(pool_size=3, strides=2))
    # Flatten and apply fullly connected layers
    alex_net.add(gluon.nn.Flatten())
    alex_net.add(gluon.nn.Dense(4096, activation="relu"))
    alex_net.add(gluon.nn.Dense(4096, activation="relu"))
    alex_net.add(gluon.nn.Dense(10))

print('[DONE]')


def evaluate_accuracy(data_iterator, net, ctx):
    acc = mx.metric.Accuracy()
    for d, l in data_iterator:
        data = d.as_in_context(ctx[0])
        label = l.as_in_context(ctx[0])
        output = net(data)
        predictions = nd.argmax(output, axis=1)
        acc.update(preds=predictions, labels=label)
    return acc.get()[1]


def forward_backward(net, data, label):
    with autograd.record():
        losses = [softmax_cross_entropy(net(X), Y) for X, Y in zip(data, label)]
    for l in losses:
        l.backward()


def train_batch(batch, ctx, net, trainer):
    data = gluon.utils.split_and_load(batch[0], ctx)
    label = gluon.utils.split_and_load(batch[1], ctx)
    # compute gradient
    forward_backward(net, data, label)
    # update parameters
    trainer.step(batch[0].shape[0])



softmax_cross_entropy = gluon.loss.SoftmaxCrossEntropyLoss()

def run(num_gpus, batch_size, lr, epochs=5):
    # the list of GPUs will be used

    durations = []
    accuracies = []

    smoothing_constant = .01

    ctx = [mx.gpu(i) for i in range(num_gpus)]
    print('Running on {}'.format(ctx))


    print('Batch size is {}'.format(batch_size))

    print('initalizing parameters')
    # alex_net.collect_params().initialize(force_reinit=True, ctx=ctx)
    alex_net.collect_params().initialize(mx.init.Xavier(magnitude=2.24), force_reinit=True, ctx=ctx)
    print('initalizing trainer')
    trainer = gluon.Trainer(alex_net.collect_params(), 'sgd', {'learning_rate': lr})




    for epoch in range(epochs):
        # train
        start = time()
        for batch_num, (data, label) in enumerate(train_data):
            train_batch([data, label], ctx, alex_net, trainer)

        nd.waitall()  # wait until all computations are finished to benchmark the time
        epoch_train_time = time()-start

        durations.append(epoch_train_time)

        print('Epoch %d, training time = %.1f sec'%(epoch, epoch_train_time))

        # validating

        correct, num = 0.0, 0.0
        acc = evaluate_accuracy(test_data, alex_net, ctx)
        print('\t\tValidation accuracy = %.4f'%(acc))

        accuracies.append(acc)

    return {'duration': durations, 'accuracy': accuracies}



data = {}
for gpus in [1,2,4,8]:
    print('running with {} GPUs'.format(gpus))
    da = run(gpus, 12*gpus, .3, 10)
    data[str(gpus)] = da

print(json.dumps(data))

```

# Output with 8
```
[LOAD]: CIFAR10 TRAIN
[LOADED]
[LOAD]: CIFAR10 TEST
[LOADED]
[DEF]: ALEX NET
[DONE]
running with 8 GPUs
Running on [gpu(0), gpu(1), gpu(2), gpu(3), gpu(4), gpu(5), gpu(6), gpu(7)]
Batch size is 96
initalizing parameters
initalizing trainer
[17:21:53] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[17:21:53] src/kvstore/././comm.h:327: only 32 out of 56 GPU pairs are enabled direct access. It may affect the performance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off
[17:21:53] src/kvstore/././comm.h:336: .vvvv...
[17:21:53] src/kvstore/././comm.h:336: v.vv.v..
[17:21:53] src/kvstore/././comm.h:336: vv.v..v.
[17:21:53] src/kvstore/././comm.h:336: vvv....v
[17:21:53] src/kvstore/././comm.h:336: v....vvv
[17:21:53] src/kvstore/././comm.h:336: .v..v.vv
[17:21:53] src/kvstore/././comm.h:336: ..v.vv.v
[17:21:53] src/kvstore/././comm.h:336: ...vvvv.
Epoch 0, training time = 70.6 sec
		Validation accuracy = 0.1000
Epoch 1, training time = 72.5 sec
		Validation accuracy = 0.1000
Epoch 2, training time = 72.5 sec
		Validation accuracy = 0.1000
Epoch 3, training time = 71.3 sec
		Validation accuracy = 0.1000
Epoch 4, training time = 70.6 sec
		Validation accuracy = 0.1000
Epoch 5, training time = 69.3 sec
		Validation accuracy = 0.1000
Epoch 6, training time = 70.1 sec
		Validation accuracy = 0.1000
Epoch 7, training time = 69.6 sec
		Validation accuracy = 0.1000
Epoch 8, training time = 70.2 sec
		Validation accuracy = 0.1000
Epoch 9, training time = 69.9 sec
		Validation accuracy = 0.1000

```

# Output with 1

```
[LOAD]: CIFAR10 TRAIN
[LOADED]
[LOAD]: CIFAR10 TEST
[LOADED]
[DEF]: ALEX NET
[DONE]
running with 1 GPUs
Running on [gpu(0)]
Batch size is 12
initalizing parameters
initalizing trainer
[17:36:51] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[17:36:58] /opt/mxnet/dmlc-core/include/dmlc/./logging.h:308: [17:36:58] src/storage/./pooled_storage_manager.h:111: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd3561641fc]
[bt] (1) /usr/local/lib/libmxnet.so(_ZN5mxnet7storage23GPUPooledStorageManager5AllocEm+0x163) [0x7fd357174b93]
[bt] (2) /usr/local/lib/libmxnet.so(_ZN5mxnet11StorageImpl5AllocEmNS_7ContextE+0x69) [0x7fd357178069]
[bt] (3) /usr/local/lib/libmxnet.so(+0x173d16f) [0x7fd3571e916f]
[bt] (4) /usr/local/lib/libmxnet.so(_ZN5mxnet4exec13GraphExecutor19InitDataEntryMemoryEPSt6vectorINS_7NDArrayESaIS3_EE+0x2a54) [0x7fd3571f1c24]
[bt] (5) /usr/local/lib/libmxnet.so(_ZN5mxnet4exec13GraphExecutor15FinishInitGraphEN4nnvm6SymbolENS2_5GraphEPNS_8ExecutorERKSt13unordered_mapINS2_9NodeEntryENS_7NDArrayENS2_13NodeEntryHashENS2_14NodeEntryEqualESaISt4pairIKS8_S9_EEE+0xa11) [0x7fd3571f84f1]
[bt] (6) /usr/local/lib/libmxnet.so(_ZN5mxnet4exec13GraphExecutor4InitEN4nnvm6SymbolERKNS_7ContextERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_St4lessISD_ESaISt4pairIKSD_S4_EEERKSt6vectorINS_7NDArrayESaISO_EESS_RKSN_INS_9OpReqTypeESaIST_EESS_PNS_8ExecutorERKSt13unordered_mapINS2_9NodeEntryESO_NS2_13NodeEntryHashENS2_14NodeEntryEqualESaISG_IKS11_SO_EEE+0x14d5) [0x7fd3571f9ab5]
[bt] (7) /usr/local/lib/libmxnet.so(_ZN5mxnet8autograd15AutogradRuntime15ComputeGradientERKSt6vectorINS_7NDArrayESaIS3_EES7_bb+0x35e0) [0x7fd356dff2f0]
[bt] (8) /usr/local/lib/libmxnet.so(MXAutogradBackwardEx+0x8a0) [0x7fd35719f420]
[bt] (9) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7fd395e98e20]

Traceback (most recent call last):
  File "dcnn.py", line 142, in <module>
    da = run(gpus, 12*gpus, .3, 10)
  File "dcnn.py", line 118, in run
    train_batch([data, label], ctx, alex_net, trainer)
  File "dcnn.py", line 83, in train_batch
    forward_backward(net, data, label)
  File "dcnn.py", line 72, in forward_backward
    l.backward()
  File "/opt/mxnet/python/mxnet/ndarray.py", line 1102, in backward
    ctypes.c_int(train_mode)))
  File "/opt/mxnet/python/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:36:58] src/storage/./pooled_storage_manager.h:111: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd3561641fc]
[bt] (1) /usr/local/lib/libmxnet.so(_ZN5mxnet7storage23GPUPooledStorageManager5AllocEm+0x163) [0x7fd357174b93]
[bt] (2) /usr/local/lib/libmxnet.so(_ZN5mxnet11StorageImpl5AllocEmNS_7ContextE+0x69) [0x7fd357178069]
[bt] (3) /usr/local/lib/libmxnet.so(+0x173d16f) [0x7fd3571e916f]
[bt] (4) /usr/local/lib/libmxnet.so(_ZN5mxnet4exec13GraphExecutor19InitDataEntryMemoryEPSt6vectorINS_7NDArrayESaIS3_EE+0x2a54) [0x7fd3571f1c24]
[bt] (5) /usr/local/lib/libmxnet.so(_ZN5mxnet4exec13GraphExecutor15FinishInitGraphEN4nnvm6SymbolENS2_5GraphEPNS_8ExecutorERKSt13unordered_mapINS2_9NodeEntryENS_7NDArrayENS2_13NodeEntryHashENS2_14NodeEntryEqualESaISt4pairIKS8_S9_EEE+0xa11) [0x7fd3571f84f1]
[bt] (6) /usr/local/lib/libmxnet.so(_ZN5mxnet4exec13GraphExecutor4InitEN4nnvm6SymbolERKNS_7ContextERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_St4lessISD_ESaISt4pairIKSD_S4_EEERKSt6vectorINS_7NDArrayESaISO_EESS_RKSN_INS_9OpReqTypeESaIST_EESS_PNS_8ExecutorERKSt13unordered_mapINS2_9NodeEntryESO_NS2_13NodeEntryHashENS2_14NodeEntryEqualESaISG_IKS11_SO_EEE+0x14d5) [0x7fd3571f9ab5]
[bt] (7) /usr/local/lib/libmxnet.so(_ZN5mxnet8autograd15AutogradRuntime15ComputeGradientERKSt6vectorINS_7NDArrayESaIS3_EES7_bb+0x35e0) [0x7fd356dff2f0]
[bt] (8) /usr/local/lib/libmxnet.so(MXAutogradBackwardEx+0x8a0) [0x7fd35719f420]
[bt] (9) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7fd395e98e20]
```

**Comment by SumNeuron** [comment]
By the way, each of these GPUs have 16GBs of ram so what is going on?

**Comment by zackchase** [comment]
@piiswrong any idea?

**Comment by samuelBB** [comment]
@SumNeuron I'm having a similar problem, were you able to find the issue?
